package Overtext;

import java.awt.Image;
import java.awt.image.BufferedImage;

import javax.swing.JPanel;

public class Varibles extends JPanel{
	public String eat = "";
	String choice2 = "";
	public Image chicken;
	public Image characterspeaking;
	public int script = 0;
	public BufferedImage bakeing;
	public  BufferedImage tiles[];
	public int background;
	public Image intro;
	boolean start = false; 
	public int x = 189;
	public int y = 100;
	public int backgroundcheck = 0;
	public int earthchanspeaking = 0;
	//and the bx and by values became the characters
	public int bx = 500;
	public boolean stop = false;
	public boolean attackphase = false;
	public boolean abilitytomove = true;
	public boolean tutorial = true;
	public boolean changegame = false;
	public boolean Dokistarted = false;
	public boolean spikeup = true;
	public int checkthat = 1;
	public int by = 700;
	public int test = 50;
	public int test2 = 500;
	public int bxvelocity = 0;
	public int edgeofscreen = 1224;
	public int byvelocity = 0;
	public int Audreyhealth = 20;
	public int jakehealth = 20;
	public int chrishealth = 20;
	public int backpackspace;
	public int packspacetooken;
	public int chrisdamage[] = {5,6,7,8,9,10};
	public int jakedamage[] = {5,6,7,8,9,10};
	public int chrisxp = 0;
	public int jakexp = 0;
	public int Jakex = 600;
	public int Chrisx = 250;
	public int swordx = 260;
	public int Jakey = 300;
	public int Chrisy = 300;
	public int swordy = 200;
	public int checkChrisx;
	public int checkChrisy;
	public int checkJakey;
	public int checkJakex;
	public int checkAudreyy;
	public int checkAudreyx;
	public int Audreyx;
	public int choiceattack = 0;
	public int chickenx = 900;
	public int chickeny = 150;
	public int chickenhealth = 15;
	public int cursorx = 250;
	public int cursory = 700;
	public int mouseX;
	public int mouseY;
	public int entertimes = 0;
	public int characterspeaking3x = 580;
	public int characterspeaking3y = 250;
	public int characterspeaking4x = 780;
	public int characterspeaking4y = 250;
	public int characterspeaking2x = 20;
	public int characterspeaking2y = 250;
	public int backpackthings = 0;
	public int backpackthingsmax = 20;
	public int chicken2y = 500;
	public int chicken2x = 450;
	public int chicken3y;
	public int chicken3x;
	public int chicken4y;
	public int chicken4x;
	public int chicken5y;
	public int chicken5x;
	public int xVelocity;
	public int yVelocity;
	public int spikesx = 350;
	public int spikesy = 300;
	public int xVelocity2;
	public int yVelocity2;
	public int spikes2x = 500;
	public int spikes2y = -100;
	public int xVelocity3;
	public int yVelocity3;
	public int spikes3x = 100;
	public int spikes3y = 100;
	public Image backround;
	public Image Chris;
	public Image Jake;
	public Image Audrey;
	public Image textbox;
	public Image Earthchan;
	public Image eartchpic;
	public Image cursor;
	public Image chrischaracter;
	public Image textbox2;
	public Image characterspeaking2;
	public Image characterspeaking3;
	public Image characterspeaking4;
    public Image sword;
    
}
